//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Locations = new HashSet<Location>();
            this.DoctorPatientAppointments = new HashSet<DoctorPatientAppointment>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Specialty Specialty { get; set; }
    
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<DoctorPatientAppointment> DoctorPatientAppointments { get; set; }
    }
}
