//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.DoctorPatientAppointments = new HashSet<DoctorPatientAppointment>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DateOfBirth { get; set; }
        public int LoginId { get; set; }
        public int AddressId { get; set; }
    
        public virtual ICollection<DoctorPatientAppointment> DoctorPatientAppointments { get; set; }
        public virtual Address Address { get; set; }
    }
}
