//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receptionist
    {
        public Receptionist()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int Id { get; set; }
        public int LoginId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
