//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAppointment
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
