//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointo.Entity
{
    using System;
    
    public enum Specialty : int
    {
        General = 0,
        Pediatrics = 1,
        Neurologist = 2,
        Psychiatrist = 3,
        Oncologist = 4
    }
}
